### PR TITLE
Remove the HTCondor-CE init script on EL7 (SOFTWARE-2419)

### PR DESCRIPTION
**Pull request by brianhlin**
- EL7 tmpfs support
- Run against `osg-test` trunk for tests that accommodate this PR

### CODE REVIEW

**Comment by brianhlin** [comment]
@axs-gentoo: Hey Ian, since you submitted #103 for tmpfs dir creation, would you be able to check out `config/condor-ce.conf` and `config/condor-ce-collector.conf` in 5b47d07 and verify that they look ok? I haven't worked with systemd-tmpfiles before.

**Comment by djw8605** [comment]
Read through the changes, looks good to me.

**Comment by axs-gentoo** [comment]
I concurr -- these look good.  I didn't see a need for /var/lock/condor-ce/user when I was running into issues, but it won't hurt to have it there for sure.  Note also that we should likely file a condor-cron.conf for that project too, to match.

**Comment by brianhlin** [comment]
Ticket for condor-cron created [here](https://jira.opensciencegrid.org/browse/SOFTWARE-2439).

**Pull request merged**
