### PR TITLE
Explicitly set ALLOW_READ to support HTCondor 8.9.0 (SOFTWARE-3538)

### PR DESCRIPTION
**Pull request by brianhlin**
This is the default value in < HTCondor 8.9.0.

### CODE REVIEW

**Comment by brianhlin** [comment]
@timtheisen I need a personal condor config to make our 8.8.x tests whole. Do you have one handy?

**Comment by timtheisen** [comment]
Here is what we use:
~~~~
# HTCONDOR CONFIGURATION TO CREATE A POOL WITH ONE MACHINE
#
# This file was created upon initial installation of HTCondor.
# It contains configuration settings to set up a secure HTCondor
# installation consisting of **just one single machine**.
# YOU WILL WANT TO REMOVE THIS FILE IF/WHEN YOU DECIDE TO ADD ADDITIONAL
# MACHINES TO YOUR HTCONDOR INSTALLATION!  Most of these settings do
# not make sense if you have a multi-server pool.
#
# See the Quick Start Installation guide at:
#     https://research.cs.wisc.edu/htcondor/manual/quickstart.html
#

# ---  NODE ROLES  ---

# Every pool needs one Central Manager, some number of Submit nodes and
# as many Execute nodes as you can find. Consult the manual to learn
# about addtional roles.

use ROLE: CentralManager
use ROLE: Submit
use ROLE: Execute

# --- NETWORK SETTINGS ---

# Configure HTCondor services to listen to port 9618 on the IPv4
# loopback interface.
NETWORK_INTERFACE = 127.0.0.1
BIND_ALL_INTERFACES = False
CONDOR_HOST = 127.0.0.1

# --- SECURITY SETTINGS ---

# Verify authenticity of HTCondor services by checking if they are
# running with an effective user id of user "condor".
SEC_DEFAULT_AUTHENTICATION = REQUIRED
SEC_DEFAULT_INTEGRITY = REQUIRED
ALLOW_DAEMON = condor@$(UID_DOMAIN)
ALLOW_NEGOTIATOR = condor@$(UID_DOMAIN)

# Configure so only user root or user condor can run condor_on,
# condor_off, condor_restart, and condor_userprio commands to manage
# HTCondor on this machine.
# If you wish any user to do so, comment out the line below.
ALLOW_ADMINISTRATOR = root@$(UID_DOMAIN) condor@$(UID_DOMAIN)

# --- PERFORMANCE TUNING SETTINGS ---

# Since there is just one server in this pool, we can tune various
# polling intervals to be much more responsive than the system defaults
# (which are tuned for pools with thousands of servers).  This will
# enable jobs to be scheduled faster, and job monitoring to happen more
# frequently.
SCHEDD_INTERVAL = 5
NEGOTIATOR_INTERVAL = 2
NEGOTIATOR_CYCLE_DELAY = 5
STARTER_UPDATE_INTERVAL = 5
SHADOW_QUEUE_UPDATE_INTERVAL = 10
UPDATE_INTERVAL = 5
RUNBENCHMARKS = 0
JAVA_BENCHMARK_TIME = 0

# --- COMMON CHANGES ---

# Uncomment the lines below and do 'sudo condor_reconfig' if you wish
# condor_q to show jobs from all users with one line per job by default.
#CONDOR_Q_DASH_BATCH_IS_DEFAULT = False
#CONDOR_Q_ONLY_MY_JOBS = False
~~~~

**Comment by brianhlin** [comment]
@timtheisen I saw that there's a `minicondor` package available in 8.8.x. Does that provide the same config?

**Comment by timtheisen** [comment]
The removal of `NETWORK_INTERFACE=eth0` is what got the tests working.
At this point, I would also remove the `BIND_ALL_INTERFACES` line. It is unnecessary.

**Comment by brianhlin** [comment]
I think removing `BIND_ALL_INTERFACES` breaks the CE portion (atm, the CE and the personal condor each run the same `99-local.config`), possibly due to GSI auth:

https://travis-ci.org/brianhlin/htcondor-ce/builds/491866901?utm_medium=notification&utm_source=email

**Comment by timtheisen** [comment]
Never mind then. The bind all interfaces is required for the CE, but not the local HTCondor. Given that information, it looks good to me.

**Pull request merged**
