### PR TITLE
Fix condor_ce_metric errors in GangliaLog

### PR DESCRIPTION
**Pull request by brianhlin**
- Fixed missing options to condor_ce_metric
- Fixed incorrect number of arguments to rrd generation function. I set the host to `None`, similar to the following line in [condor_ce_jobmetrics](https://github.com/opensciencegrid/htcondor-ce/blob/master/src/condor_ce_jobmetrics#L147) but I'm not sure that's the correct value. @bbockelm, could you take a look at this?

I've verified that there are no more errors in `GangliaLog` and it appears that things are being published properly now:

```
04/05/16 14:59:31 publishing CollectorRecentDaemonCoreDutyCycle=2.1121, group=HTCondor Collector, units=%, derivative=0, type=float, title=, desc=Recent fraction of busy time in the daemon event loop, cluster=, spoof_host=131.225.154.185:fermicloud050.fnal.gov
04/05/16 14:59:31 publishing SchedulerRecentDaemonCoreDutyCycle=0.27839, group=HTCondor Schedd, units=%, derivative=0, type=float, title=, desc=Recent fraction of busy time in the daemon event loop, cluster=, spoof_host=131.225.154.185:fermicloud050.fnal.gov
04/05/16 14:59:31 publishing Availability=100, group=HTCondor Schedd, units=%, derivative=0, type=int32, title=, desc=Average availability of CE, cluster=, spoof_host=131.225.154.185:fermicloud050.fnal.gov
```

However, I was not able to actually see the CEView site to verify that the graphs looked correct.

### CODE REVIEW

**Comment by bbockelm** [comment]
Still at Puerto Rico and barely treading water in my inbox.  @djw8605 could you review instead?

**Comment by djw8605** [comment]
Yes, I will test this.

**Comment by brianhlin** [comment]
https://koji-hub.batlab.org/koji/taskinfo?taskID=208086
https://koji-hub.batlab.org/koji/taskinfo?taskID=208087

**Comment by djw8605** [comment]
I'm getting the below error.  I think you missed a call to get_rrd_name?

```
04/19/16 18:10:26  ENGINE TypeError('get_rrd_name() takes at least 3 arguments (2 given)',)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
    req.respond()
  File "/usr/lib/python2.6/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python2.6/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2115, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cptree.py", line 290, in __call__
    return app(environ, start_response)
  File "/usr/share/condor-ce/condor_ce_view", line 128, in __call__
    retval = self.app(environ, custom_start_response)
  File "/usr/lib/python2.6/site-packages/htcondorce/web.py", line 497, in application
    return callback(environ, start_response)
  File "/usr/lib/python2.6/site-packages/htcondorce/web.py", line 283, in pilots
    fname = htcondorce.rrd.get_rrd_name(environ, "pilots")
TypeError: get_rrd_name() takes at least 3 arguments (2 given)
```

**Comment by brianhlin** [comment]
@djw8605: I'm going to have to revert some of my changes but I think I'm on the right path. 

@bbockelm: it looks like you made some [changes](https://github.com/opensciencegrid/htcondor-ce/commit/9b712c8236239a14d4f1291f2bc8dae22f69dbe3#diff-f153d5d53bada68eb48c96aac4decac3L26) to `check_rrd` to support multiple CEs but [this](https://github.com/opensciencegrid/htcondor-ce/blob/master/src/condor_ce_metric#L36) wasn't updated. What should the `host` argument be here? Does it need to be changed so that `condor_ce_metric` creates metric subfolders per CE host?

**Comment by bbockelm** [comment]
I'm getting a little fuzzy on some of this code (mostly it's been handed off to Derek).  IIRC, the idea was that when run in CE mode, there's no subdirectories - those are only made when in grid-wide mode.

**Comment by brianhlin** [comment]
So you would expect `/var/log/condor-ce/spool/ceview` to look like the following for CE mode:

- ceview
   - jobs
   - metrics

And for grid-wide mode:

- ceview
   - host1
      - jobs
      - metrics
   - host2
      - jobs
      - metrics

Is that correct?

**Comment by bbockelm** [comment]
Yup, that's what I recall.

Whether that even remotely matches the code at this point, I have no clue.

**Comment by brianhlin** [comment]
@djw8605: This works on a clean install for me. Could you test this with my scratch build [here](https://koji-hub.batlab.org/koji/taskinfo?taskID=208383)?

**Pull request merged**
