### PR TITLE
Add a default route for BOSCO (SOFTWARE-2370)

### PR DESCRIPTION
**Pull request by matyasselmeci**
Add a file with `JOB_ROUTER_ENTRIES` for submitting to BOSCO. This will be in a new subpackage of `htcondor-ce` called `htcondor-ce-bosco`.

### CODE REVIEW

**Comment by djw8605** [comment]
The `osg-configure` will set those variables?   `$(BOSCO_RMS)` and `$(BOSCO_ENDPOINT)`?

**Comment by matyasselmeci** [comment]
Yes.

**Comment by djw8605** [comment]
The `osg-ce-bosco` package should also be made to depend on the new htcondor-ce-bosco package.

**Comment by matyasselmeci** [comment]
Yep, that's part of SOFTWARE-2370 (though I guess it's kind of hidden at the bottom of the description...)

**Pull request merged**
