### PR TITLE
Adding default memory to queue information

### PR DESCRIPTION
**Pull request by djw8605**
This failed for sites which did not set memory in the
resource catalog.

### CODE REVIEW

**Comment by brianhlin** [comment]
Shouldn't they be setting the memory in the resource catalog, though?

**Comment by djw8605** [comment]
Yes, but it shouldn't break the webpage when they do not.

**Comment by brianhlin** [comment]
Sure but I we should be directing the user to fix the root cause of the problem

**Comment by brianhlin** [comment]
@djw8605 is there an easy way to display a warning/error banner with CherryPy?

**Comment by djw8605** [comment]
This is put in a JSON that is parsed by a machine.  No human should be reading this output, and no human would see this warning.

**Comment by brianhlin** [comment]
Sorry, I'm confused. You mentioned above that without a default a webpage is breaking, which page was that?

**Comment by djw8605** [comment]
The JSON that AGIS consumes.  This site: http://collector.opensciencegrid.org/json/agis-compat

**Comment by djw8605** [comment]
Good idea on the failed-ce's.  We now need a test to make sure failed-ce's is empty.  We have check_mk testing the agis-compat URL, just another check_mk test.

**Pull request merged**
