### PR TITLE
Adding el7 test in addition to the el6

### PR DESCRIPTION
**Pull request by djw8605**
Also, adding a test to install the resulting RPMs.  Still working on test results.

### CODE REVIEW

**Comment by brianhlin** [comment]
@djw8605: Is this done? Tests look like they build EL7 successfully. Is there anything else you need to add?

**Comment by djw8605** [comment]
I disabled the install test for EL7.  HTCondor fails due to some tmp filesystem issues.  You can see the error in the [failed build](https://travis-ci.org/opensciencegrid/htcondor-ce/jobs/97712008#L1911).  It has something to do with systemd managing tmp filesystem on el7, and docker not having it.  I'm not entirely sure.

**Comment by djw8605** [comment]
@brianhlin Ok, I think I fixed the EL7 issue.  Can you review the code and merge if you like it?  We can add further tests then in another pull request building off of this work.

**Comment by bbockelm** [comment]
In particular, since we're inside a Docker container running as root ... Can we run osg-test?

**Comment by djw8605** [comment]
Lets merge this pull request and have a new pull request to add OSG-test. 

-Derek

**Pull request merged**
