### PR TITLE
Improvded GLUE2 information provider

### PR DESCRIPTION
**Pull request by lfield**
The previous previous pull request did not work as anticipated. The renaming was done but the old code was used.

### CODE REVIEW

**Comment by brianhlin** [comment]
Could we get a more descriptive commit message outlining what some of these changes are? e.g. "update to work with new glue2 provider"

**Comment by lfield** [comment]
I have updated the title. Please note that the previous PR did not update the code as expected.

**Comment by brianhlin** [comment]
@lfield I was referring to the git commit message. Could you run `git rebase` to reword it? You'll have to force-push to your branch once you've done that to overwrite the old commit.

**Comment by edquist** [comment]
@lfield @brianhlin - fyi if you just want to reword the last commit, you can also do `git commit --amend`.

(And then yes either way you need to `git push -f ...` your `provider` branch to your `lfield` remote)

**Comment by lfield** [comment]
I hope that I have done what was asked. Let me know if there is anything else.

**Pull request merged**
