### PR TITLE
HTCondor-CE BDII provider fixes

### PR DESCRIPTION
**Pull request by brianhlin**
This PR includes the following (CC @lfield):

- Move BDII code/config into `contrib/`
- Replace reference to `CENTRAL_MANAGER` with standard config val, `COLLECTOR_HOST`
- Query the CE schedd instead of the CE batch system schedd for availability and VO job numbers
- Various pylint fixes

### CODE REVIEW

**Comment by brianhlin** [comment]
Oops, a stray hunk made it into that commit somehow. I've fixed it and also should have the CI fixed, too.

**Comment by brianhlin** [comment]
Christelle from IN2P3 gave the latest version of the script a try and verified that things still work

**Comment by lfield** [comment]
This version doesn't work for us.

**Comment by brianhlin** [comment]
Hi @lfield, have you followed the instructions in [this README](https://github.com/opensciencegrid/htcondor-ce/blob/master/contrib/bdii/README.md)? Could you provide some more details on what isn't working exactly?

**Comment by lfield** [comment]
I am investigating the diffs in code and output

**Pull request merged**
