### PR TITLE
Change 'set' args around osg-test so we can get logs

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by djw8605** [comment]
I kinda wish the build would have failed to fully the change.  This change looks good to me.

**Comment by brianhlin** [comment]
If you want, I can throw in a failing command in between the `set` commands to see it fail on a separate branch.

**Comment by djw8605** [comment]
Sure!

**Comment by brianhlin** [comment]
Added a failing command in between the `set` commands and we still got the logs back! 

https://travis-ci.org/brianhlin/htcondor-ce/builds/135056411

**Pull request merged**
